markdown: rdiscount
permalink: /notes/:title.html
multiviews: true
haml: true
sass: true
source: .
destination: ./_site
rdiscount extensions: [smart]
exclude: [ .gitignore, README.md, Gemfile, Gemfile.lock, Procfile, vendor ]
